version: '3'

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./OrderEase-2B/dist/:/usr/share/nginx/html/business/
      - ./OrderEase-2C/dist/:/usr/share/nginx/html/customer/
    ports:
      - '8888:8888'  # Business Port
      - '8000:8000'  # Customer Port
    depends_on:
      - server
    networks:
      - server_nw

  server:
    build: ./Server
    restart: always
    command: bash docker-entrypoint.sh
    volumes:
      - ./Server:/code
    environment:
      - MODE
      - PRODUCTION_DATABASE_URI
      - SECRET_KEY
    depends_on:
      - database
    networks:
      - server_nw
      - database_nw
    
  database:
    image: mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - database_nw

networks:
  server_nw:
    driver: bridge
  database_nw:
    driver: bridge
